const LOADER_PUSH = 'LOADER_PUSH',
    LOADER_POP = 'LOADER_POP',
    LOADER_CLEAR = 'LOADER_CLEAR',
    AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS',
    SIGN_OUT = 'SIGN_OUT',
    INIT_MESSAGES = 'INIT_MESSAGES',
    INIT_BOARDS = 'INIT_BOARDS',
    ADD_MESSAGE = 'ADD_MESSAGE',
    SUBSCRIBE_BOARD = 'SUBSCRIBE_BOARD',
    AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export {
    INIT_MESSAGES,
    ADD_MESSAGE,
    INIT_BOARDS,
    LOADER_PUSH,
    LOADER_POP,
    LOADER_CLEAR,
    SIGN_OUT,
    SUBSCRIBE_BOARD,
    AUTHORIZATION_FAILURE,
    AUTHORIZATION_SUCCESS
};