const LOADER_PUSH = 'LOADER_PUSH',
    LOADER_POP = 'LOADER_POP',
    LOADER_CLEAR = 'LOADER_CLEAR',
    AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS',
    SIGN_OUT = 'SIGN_OUT',
    INIT_BOARD = 'INIT_BOARD',
    ADD_MESSAGE = 'ADD_MESSAGE',
    AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export {
    INIT_BOARD,
    ADD_MESSAGE,
    LOADER_PUSH,
    LOADER_POP,
    LOADER_CLEAR,
    SIGN_OUT,
    AUTHORIZATION_FAILURE,
    AUTHORIZATION_SUCCESS
};