const LOADER_PUSH = 'LOADER_PUSH',
    LOADER_POP = 'LOADER_POP',
    LOADER_CLEAR = 'LOADER_CLEAR',
    AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS',
    SIGN_OUT = 'SIGN_OUT',
    AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export {
    LOADER_PUSH,
    LOADER_POP,
    LOADER_CLEAR,
    SIGN_OUT,
    AUTHORIZATION_FAILURE,
    AUTHORIZATION_SUCCESS
};